function [] = visualize_features(features, labels, f1,f2)
%visualize_features Plots the relation between features given by f1 and f2
mu0 = mean(features(labels==0,:)); % Comedy
mu1 = mean(features(labels==1,:)); % Drama

label_names = {'Colour feature',            ...
               'Brightness feature',        ...
               'Edges feature',             ...
               'Word number feature',       ...
               'Mean Word length feature',  ...
               'Std Word length feature'}; 
           
gscatter(features(:,f1),features(:,f2),labels)
hold on
scatter(mu0(f1),mu0(f2), ...
        'MarkerEdgeColor','red', ...
        'MarkerFaceColor','yellow', ...
        'LineWidth',3)
scatter(mu1(f1),mu1(f2), ...
        'MarkerEdgeColor','blue', ...
        'MarkerFaceColor','cyan', ...
        'LineWidth',3)
title('Scatter plot of extracted feature values');
xlabel(label_names{f1})
ylabel(label_names{f2})
legend('Comedy','Drama')
end

